// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dz-market/svc-auth/internal/worker/outbox"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPublisher creates a new instance of MockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublisher {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockPublisher is an autogenerated mock type for the Publisher type
type MockPublisher struct {
	mock.Mock
}

type MockPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublisher) EXPECT() *MockPublisher_Expecter {
	return &MockPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockPublisher
func (_mock *MockPublisher) Publish(ctx context.Context, msgs []outbox.Message) []outbox.Result {
	ret := _mock.Called(ctx, msgs)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 []outbox.Result
	if returnFunc, ok := ret.Get(0).(func(context.Context, []outbox.Message) []outbox.Result); ok {
		r0 = returnFunc(ctx, msgs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]outbox.Result)
		}
	}
	return r0
}

// MockPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - msgs []outbox.Message
func (_e *MockPublisher_Expecter) Publish(ctx any, msgs any) *MockPublisher_Publish_Call {
	return &MockPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, msgs)}
}

func (_c *MockPublisher_Publish_Call) Run(run func(ctx context.Context, msgs []outbox.Message)) *MockPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []outbox.Message
		if args[1] != nil {
			arg1 = args[1].([]outbox.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPublisher_Publish_Call) Return(results []outbox.Result) *MockPublisher_Publish_Call {
	_c.Call.Return(results)
	return _c
}

func (_c *MockPublisher_Publish_Call) RunAndReturn(run func(ctx context.Context, msgs []outbox.Message) []outbox.Result) *MockPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}
