// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"
	"uuid"

	"github.com/dz-market/svc-auth/internal/worker/outbox"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// MarkFailed provides a mock function for the type MockStore
func (_mock *MockStore) MarkFailed(ctx context.Context, failures []outbox.Failure, at time.Time) error {
	ret := _mock.Called(ctx, failures, at)

	if len(ret) == 0 {
		panic("no return value specified for MarkFailed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []outbox.Failure, time.Time) error); ok {
		r0 = returnFunc(ctx, failures, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_MarkFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFailed'
type MockStore_MarkFailed_Call struct {
	*mock.Call
}

// MarkFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - failures []outbox.Failure
//   - at time.Time
func (_e *MockStore_Expecter) MarkFailed(ctx any, failures any, at any) *MockStore_MarkFailed_Call {
	return &MockStore_MarkFailed_Call{Call: _e.mock.On("MarkFailed", ctx, failures, at)}
}

func (_c *MockStore_MarkFailed_Call) Run(run func(ctx context.Context, failures []outbox.Failure, at time.Time)) *MockStore_MarkFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []outbox.Failure
		if args[1] != nil {
			arg1 = args[1].([]outbox.Failure)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_MarkFailed_Call) Return(err error) *MockStore_MarkFailed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_MarkFailed_Call) RunAndReturn(run func(ctx context.Context, failures []outbox.Failure, at time.Time) error) *MockStore_MarkFailed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPublished provides a mock function for the type MockStore
func (_mock *MockStore) MarkPublished(ctx context.Context, ids []uuid.UUID, at time.Time) error {
	ret := _mock.Called(ctx, ids, at)

	if len(ret) == 0 {
		panic("no return value specified for MarkPublished")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, ids, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_MarkPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPublished'
type MockStore_MarkPublished_Call struct {
	*mock.Call
}

// MarkPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
//   - at time.Time
func (_e *MockStore_Expecter) MarkPublished(ctx any, ids any, at any) *MockStore_MarkPublished_Call {
	return &MockStore_MarkPublished_Call{Call: _e.mock.On("MarkPublished", ctx, ids, at)}
}

func (_c *MockStore_MarkPublished_Call) Run(run func(ctx context.Context, ids []uuid.UUID, at time.Time)) *MockStore_MarkPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_MarkPublished_Call) Return(err error) *MockStore_MarkPublished_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_MarkPublished_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID, at time.Time) error) *MockStore_MarkPublished_Call {
	_c.Call.Return(run)
	return _c
}

// Unpublished provides a mock function for the type MockStore
func (_mock *MockStore) Unpublished(ctx context.Context, limit int, now time.Time) ([]outbox.Message, error) {
	ret := _mock.Called(ctx, limit, now)

	if len(ret) == 0 {
		panic("no return value specified for Unpublished")
	}

	var r0 []outbox.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time) ([]outbox.Message, error)); ok {
		return returnFunc(ctx, limit, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time) []outbox.Message); ok {
		r0 = returnFunc(ctx, limit, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]outbox.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Time) error); ok {
		r1 = returnFunc(ctx, limit, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Unpublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unpublished'
type MockStore_Unpublished_Call struct {
	*mock.Call
}

// Unpublished is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - now time.Time
func (_e *MockStore_Expecter) Unpublished(ctx any, limit any, now any) *MockStore_Unpublished_Call {
	return &MockStore_Unpublished_Call{Call: _e.mock.On("Unpublished", ctx, limit, now)}
}

func (_c *MockStore_Unpublished_Call) Run(run func(ctx context.Context, limit int, now time.Time)) *MockStore_Unpublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_Unpublished_Call) Return(messages []outbox.Message, err error) *MockStore_Unpublished_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockStore_Unpublished_Call) RunAndReturn(run func(ctx context.Context, limit int, now time.Time) ([]outbox.Message, error)) *MockStore_Unpublished_Call {
	_c.Call.Return(run)
	return _c
}
