version: "3"

dotenv:
    - .env

vars:
    MIGRATIONS_DIR: migrations

tasks:
    lint:
        desc: Run golangci-lint
        cmds:
            - golangci-lint run --timeout=5m

    lint:fix:
        desc: Run golangci-lint with autofix
        cmds:
            - golangci-lint run --fix --timeout=5m

    fix:
        desc: Rewrite code that uses outdated Go APIs
        cmds:
            - go fix ./...

    migration:create:
        desc: Create goose migration
        cmds:
            - mkdir -p {{.MIGRATIONS_DIR}}
            - goose -dir {{.MIGRATIONS_DIR}} create {{.CLI_ARGS}} sql

    migration:status:
        desc: Show migration status
        cmds:
            - goose -dir {{.MIGRATIONS_DIR}} postgres "$POSTGRES_DSN" status

    migration:up:
        desc: Apply migrations
        cmds:
            - goose -dir {{.MIGRATIONS_DIR}} postgres "$POSTGRES_DSN" up

    migration:down:
        desc: Rool back last migration
        cmds:
            - goose -dir {{.MIGRATIONS_DIR}} postgres "$POSTGRES_DSN" down