// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"
	"uuid"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAccessTokenIssuer creates a new instance of MockAccessTokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessTokenIssuer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAccessTokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAccessTokenIssuer is an autogenerated mock type for the AccessTokenIssuer type
type MockAccessTokenIssuer struct {
	mock.Mock
}

type MockAccessTokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessTokenIssuer) EXPECT() *MockAccessTokenIssuer_Expecter {
	return &MockAccessTokenIssuer_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function for the type MockAccessTokenIssuer
func (_mock *MockAccessTokenIssuer) Issue(userID uuid.UUID, sessionID uuid.UUID, issuedAt time.Time, expiresAt time.Time) (string, error) {
	ret := _mock.Called(userID, sessionID, issuedAt, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, time.Time, time.Time) (string, error)); ok {
		return returnFunc(userID, sessionID, issuedAt, expiresAt)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, time.Time, time.Time) string); ok {
		r0 = returnFunc(userID, sessionID, issuedAt, expiresAt)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = returnFunc(userID, sessionID, issuedAt, expiresAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccessTokenIssuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockAccessTokenIssuer_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - userID uuid.UUID
//   - sessionID uuid.UUID
//   - issuedAt time.Time
//   - expiresAt time.Time
func (_e *MockAccessTokenIssuer_Expecter) Issue(userID any, sessionID any, issuedAt any, expiresAt any) *MockAccessTokenIssuer_Issue_Call {
	return &MockAccessTokenIssuer_Issue_Call{Call: _e.mock.On("Issue", userID, sessionID, issuedAt, expiresAt)}
}

func (_c *MockAccessTokenIssuer_Issue_Call) Run(run func(userID uuid.UUID, sessionID uuid.UUID, issuedAt time.Time, expiresAt time.Time)) *MockAccessTokenIssuer_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAccessTokenIssuer_Issue_Call) Return(s string, err error) *MockAccessTokenIssuer_Issue_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAccessTokenIssuer_Issue_Call) RunAndReturn(run func(userID uuid.UUID, sessionID uuid.UUID, issuedAt time.Time, expiresAt time.Time) (string, error)) *MockAccessTokenIssuer_Issue_Call {
	_c.Call.Return(run)
	return _c
}
