// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dz-market/svc-auth/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOutboxRepository creates a new instance of MockOutboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboxRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockOutboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockOutboxRepository is an autogenerated mock type for the OutboxRepository type
type MockOutboxRepository struct {
	mock.Mock
}

type MockOutboxRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboxRepository) EXPECT() *MockOutboxRepository_Expecter {
	return &MockOutboxRepository_Expecter{mock: &_m.Mock}
}

// AddUserRegistered provides a mock function for the type MockOutboxRepository
func (_mock *MockOutboxRepository) AddUserRegistered(ctx context.Context, e user.Registered) error {
	ret := _mock.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for AddUserRegistered")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.Registered) error); ok {
		r0 = returnFunc(ctx, e)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOutboxRepository_AddUserRegistered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserRegistered'
type MockOutboxRepository_AddUserRegistered_Call struct {
	*mock.Call
}

// AddUserRegistered is a helper method to define mock.On call
//   - ctx context.Context
//   - e user.Registered
func (_e *MockOutboxRepository_Expecter) AddUserRegistered(ctx any, e any) *MockOutboxRepository_AddUserRegistered_Call {
	return &MockOutboxRepository_AddUserRegistered_Call{Call: _e.mock.On("AddUserRegistered", ctx, e)}
}

func (_c *MockOutboxRepository_AddUserRegistered_Call) Run(run func(ctx context.Context, e user.Registered)) *MockOutboxRepository_AddUserRegistered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.Registered
		if args[1] != nil {
			arg1 = args[1].(user.Registered)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutboxRepository_AddUserRegistered_Call) Return(err error) *MockOutboxRepository_AddUserRegistered_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOutboxRepository_AddUserRegistered_Call) RunAndReturn(run func(ctx context.Context, e user.Registered) error) *MockOutboxRepository_AddUserRegistered_Call {
	_c.Call.Return(run)
	return _c
}
