// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPasswordHasher creates a new instance of MockPasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordHasher {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockPasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockPasswordHasher is an autogenerated mock type for the PasswordHasher type
type MockPasswordHasher struct {
	mock.Mock
}

type MockPasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordHasher) EXPECT() *MockPasswordHasher_Expecter {
	return &MockPasswordHasher_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function for the type MockPasswordHasher
func (_mock *MockPasswordHasher) Hash(ctx context.Context, password string) (string, error) {
	ret := _mock.Called(ctx, password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordHasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockPasswordHasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - ctx context.Context
//   - password string
func (_e *MockPasswordHasher_Expecter) Hash(ctx any, password any) *MockPasswordHasher_Hash_Call {
	return &MockPasswordHasher_Hash_Call{Call: _e.mock.On("Hash", ctx, password)}
}

func (_c *MockPasswordHasher_Hash_Call) Run(run func(ctx context.Context, password string)) *MockPasswordHasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasswordHasher_Hash_Call) Return(s string, err error) *MockPasswordHasher_Hash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPasswordHasher_Hash_Call) RunAndReturn(run func(ctx context.Context, password string) (string, error)) *MockPasswordHasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockPasswordHasher
func (_mock *MockPasswordHasher) Verify(ctx context.Context, password string, passwordHash string) (bool, error) {
	ret := _mock.Called(ctx, password, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, password, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, password, passwordHash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, password, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordHasher_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockPasswordHasher_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - password string
//   - passwordHash string
func (_e *MockPasswordHasher_Expecter) Verify(ctx any, password any, passwordHash any) *MockPasswordHasher_Verify_Call {
	return &MockPasswordHasher_Verify_Call{Call: _e.mock.On("Verify", ctx, password, passwordHash)}
}

func (_c *MockPasswordHasher_Verify_Call) Run(run func(ctx context.Context, password string, passwordHash string)) *MockPasswordHasher_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPasswordHasher_Verify_Call) Return(b bool, err error) *MockPasswordHasher_Verify_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPasswordHasher_Verify_Call) RunAndReturn(run func(ctx context.Context, password string, passwordHash string) (bool, error)) *MockPasswordHasher_Verify_Call {
	_c.Call.Return(run)
	return _c
}
