// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRefreshTokenGenerator creates a new instance of MockRefreshTokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenGenerator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRefreshTokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRefreshTokenGenerator is an autogenerated mock type for the RefreshTokenGenerator type
type MockRefreshTokenGenerator struct {
	mock.Mock
}

type MockRefreshTokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenGenerator) EXPECT() *MockRefreshTokenGenerator_Expecter {
	return &MockRefreshTokenGenerator_Expecter{mock: &_m.Mock}
}

// Fingerprint provides a mock function for the type MockRefreshTokenGenerator
func (_mock *MockRefreshTokenGenerator) Fingerprint(value string) []byte {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for Fingerprint")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockRefreshTokenGenerator_Fingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fingerprint'
type MockRefreshTokenGenerator_Fingerprint_Call struct {
	*mock.Call
}

// Fingerprint is a helper method to define mock.On call
//   - value string
func (_e *MockRefreshTokenGenerator_Expecter) Fingerprint(value any) *MockRefreshTokenGenerator_Fingerprint_Call {
	return &MockRefreshTokenGenerator_Fingerprint_Call{Call: _e.mock.On("Fingerprint", value)}
}

func (_c *MockRefreshTokenGenerator_Fingerprint_Call) Run(run func(value string)) *MockRefreshTokenGenerator_Fingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRefreshTokenGenerator_Fingerprint_Call) Return(bytes []byte) *MockRefreshTokenGenerator_Fingerprint_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockRefreshTokenGenerator_Fingerprint_Call) RunAndReturn(run func(value string) []byte) *MockRefreshTokenGenerator_Fingerprint_Call {
	_c.Call.Return(run)
	return _c
}

// Generate provides a mock function for the type MockRefreshTokenGenerator
func (_mock *MockRefreshTokenGenerator) Generate() (string, []byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (string, []byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() []byte); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRefreshTokenGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockRefreshTokenGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *MockRefreshTokenGenerator_Expecter) Generate() *MockRefreshTokenGenerator_Generate_Call {
	return &MockRefreshTokenGenerator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *MockRefreshTokenGenerator_Generate_Call) Run(run func()) *MockRefreshTokenGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRefreshTokenGenerator_Generate_Call) Return(s string, bytes []byte, err error) *MockRefreshTokenGenerator_Generate_Call {
	_c.Call.Return(s, bytes, err)
	return _c
}

func (_c *MockRefreshTokenGenerator_Generate_Call) RunAndReturn(run func() (string, []byte, error)) *MockRefreshTokenGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}
