// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dz-market/svc-auth/internal/domain/session"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRefreshTokensRepository creates a new instance of MockRefreshTokensRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokensRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokensRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRefreshTokensRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRefreshTokensRepository is an autogenerated mock type for the RefreshTokensRepository type
type MockRefreshTokensRepository struct {
	mock.Mock
}

type MockRefreshTokensRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokensRepository) EXPECT() *MockRefreshTokensRepository_Expecter {
	return &MockRefreshTokensRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRefreshTokensRepository
func (_mock *MockRefreshTokensRepository) Create(ctx context.Context, t session.RefreshToken) error {
	ret := _mock.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.RefreshToken) error); ok {
		r0 = returnFunc(ctx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokensRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRefreshTokensRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t session.RefreshToken
func (_e *MockRefreshTokensRepository_Expecter) Create(ctx any, t any) *MockRefreshTokensRepository_Create_Call {
	return &MockRefreshTokensRepository_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *MockRefreshTokensRepository_Create_Call) Run(run func(ctx context.Context, t session.RefreshToken)) *MockRefreshTokensRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 session.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(session.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokensRepository_Create_Call) Return(err error) *MockRefreshTokensRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokensRepository_Create_Call) RunAndReturn(run func(ctx context.Context, t session.RefreshToken) error) *MockRefreshTokensRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
