// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"uuid"

	"github.com/dz-market/svc-auth/internal/domain/session"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionsRepository creates a new instance of MockSessionsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionsRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSessionsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSessionsRepository is an autogenerated mock type for the SessionsRepository type
type MockSessionsRepository struct {
	mock.Mock
}

type MockSessionsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionsRepository) EXPECT() *MockSessionsRepository_Expecter {
	return &MockSessionsRepository_Expecter{mock: &_m.Mock}
}

// ByID provides a mock function for the type MockSessionsRepository
func (_mock *MockSessionsRepository) ByID(ctx context.Context, id uuid.UUID) (session.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 session.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (session.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) session.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(session.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionsRepository_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type MockSessionsRepository_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSessionsRepository_Expecter) ByID(ctx any, id any) *MockSessionsRepository_ByID_Call {
	return &MockSessionsRepository_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *MockSessionsRepository_ByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSessionsRepository_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionsRepository_ByID_Call) Return(session1 session.Session, err error) *MockSessionsRepository_ByID_Call {
	_c.Call.Return(session1, err)
	return _c
}

func (_c *MockSessionsRepository_ByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (session.Session, error)) *MockSessionsRepository_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockSessionsRepository
func (_mock *MockSessionsRepository) Create(ctx context.Context, s session.Session) error {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.Session) error); ok {
		r0 = returnFunc(ctx, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionsRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionsRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s session.Session
func (_e *MockSessionsRepository_Expecter) Create(ctx any, s any) *MockSessionsRepository_Create_Call {
	return &MockSessionsRepository_Create_Call{Call: _e.mock.On("Create", ctx, s)}
}

func (_c *MockSessionsRepository_Create_Call) Run(run func(ctx context.Context, s session.Session)) *MockSessionsRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 session.Session
		if args[1] != nil {
			arg1 = args[1].(session.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionsRepository_Create_Call) Return(err error) *MockSessionsRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionsRepository_Create_Call) RunAndReturn(run func(ctx context.Context, s session.Session) error) *MockSessionsRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
