http:
    addr: ${HTTP_ADDR}
    read_header_timeout: 5s
    read_timeout: 10s
    write_timeout: 10s
    idle_timeout: 60s

grpc:
    addr: ${GRPC_ADDR}

postgres:
    dsn: ${POSTGRES_DSN}
    min_conns: 1
    max_conns: 10
    connect_timeout: 5s
    max_conn_lifetime: 30m

tokens:
    access:
        secret: ${ACCESS_TOKEN_SECRET}
        TTL: 15m
    refresh:
        ttl: 720h
        byte_len: 32

log:
    level: info

shutdown_timeout: 10s