// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dz-market/svc-auth/internal/application/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(ctx context.Context, in auth.LoginInput) (auth.LoginOutput, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 auth.LoginOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.LoginInput) (auth.LoginOutput, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.LoginInput) auth.LoginOutput); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(auth.LoginOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.LoginInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - in auth.LoginInput
func (_e *MockAuthService_Expecter) Login(ctx any, in any) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, in)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, in auth.LoginInput)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.LoginInput
		if args[1] != nil {
			arg1 = args[1].(auth.LoginInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(loginOutput auth.LoginOutput, err error) *MockAuthService_Login_Call {
	_c.Call.Return(loginOutput, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(ctx context.Context, in auth.LoginInput) (auth.LoginOutput, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Logout(ctx context.Context, in auth.LogoutInput) error {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.LogoutInput) error); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - in auth.LogoutInput
func (_e *MockAuthService_Expecter) Logout(ctx any, in any) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, in)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(ctx context.Context, in auth.LogoutInput)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.LogoutInput
		if args[1] != nil {
			arg1 = args[1].(auth.LogoutInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(err error) *MockAuthService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(ctx context.Context, in auth.LogoutInput) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Refresh(ctx context.Context, in auth.RefreshInput) (auth.RefreshOutput, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 auth.RefreshOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.RefreshInput) (auth.RefreshOutput, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.RefreshInput) auth.RefreshOutput); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(auth.RefreshOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.RefreshInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockAuthService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - in auth.RefreshInput
func (_e *MockAuthService_Expecter) Refresh(ctx any, in any) *MockAuthService_Refresh_Call {
	return &MockAuthService_Refresh_Call{Call: _e.mock.On("Refresh", ctx, in)}
}

func (_c *MockAuthService_Refresh_Call) Run(run func(ctx context.Context, in auth.RefreshInput)) *MockAuthService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.RefreshInput
		if args[1] != nil {
			arg1 = args[1].(auth.RefreshInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Refresh_Call) Return(refreshOutput auth.RefreshOutput, err error) *MockAuthService_Refresh_Call {
	_c.Call.Return(refreshOutput, err)
	return _c
}

func (_c *MockAuthService_Refresh_Call) RunAndReturn(run func(ctx context.Context, in auth.RefreshInput) (auth.RefreshOutput, error)) *MockAuthService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Register(ctx context.Context, in auth.RegisterInput) (auth.RegisterOutput, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 auth.RegisterOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.RegisterInput) (auth.RegisterOutput, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.RegisterInput) auth.RegisterOutput); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(auth.RegisterOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.RegisterInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - in auth.RegisterInput
func (_e *MockAuthService_Expecter) Register(ctx any, in any) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, in)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, in auth.RegisterInput)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.RegisterInput
		if args[1] != nil {
			arg1 = args[1].(auth.RegisterInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(registerOutput auth.RegisterOutput, err error) *MockAuthService_Register_Call {
	_c.Call.Return(registerOutput, err)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(ctx context.Context, in auth.RegisterInput) (auth.RegisterOutput, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}
